# Generated by Django 4.2.7 on 2023-12-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_subject", models.CharField(max_length=500)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Email Recipient",
                "verbose_name_plural": "Email Recipients",
                "unique_together": {("email_subject", "email")},
            },
        ),
    ]
