# Generated by Django 4.2.7 on 2024-12-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[
                    ("EMAIL", "EMAIL"),
                    ("GOOGLE", "GOOGLE"),
                    ("choices", "choices"),
                ],
                default="email",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
