# Generated by Django 4.2.7 on 2023-12-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizers", "0002_emailrecipient"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="emailrecipient",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="emailrecipient",
            name="email_subject",
        ),
        migrations.AddField(
            model_name="emailrecipient",
            name="email_subject",
            field=models.ManyToManyField(to="organizers.emailsubject"),
        ),
    ]
