# Generated by Django 4.2.7 on 2024-12-27 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizers", "0002_user_auth_provider_user_is_verified"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailRecipient",
        ),
        migrations.DeleteModel(
            name="EmailSubject",
        ),
    ]
