# Generated by Django 4.2.7 on 2023-12-18 03:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "organizers",
            "0003_emailsubject_alter_emailrecipient_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailrecipient",
            old_name="email_subject",
            new_name="email_subjects",
        ),
    ]
