# Generated by Django 4.2.7 on 2024-12-25 21:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_donor_alter_donation_donor"),
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Donor",
        ),
    ]
