# Generated by Django 4.2.7 on 2025-07-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0002_delete_donor"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="hall_off_residence",
            field=models.CharField(default="Mellanby", max_length=100),
            preserve_default=False,
        ),
    ]
